services:
  - type: web
    name: control_escolar_desit_api
    env: python
    plan: free
    buildCommand: pip install --no-cache-dir -r requirements.txt && python manage.py collectstatic --no-input
    startCommand: gunicorn app_movil_escolar_api.wsgi:application --bind 0.0.0.0:$PORT --workers 1
    envVars:
      - key: SECRET_KEY
        scope: build
        value: your-secret-key-here-change-this
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: control_escolar_desit_db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "*.onrender.com,localhost,127.0.0.1"

  - type: pserv
    name: control_escolar_desit_db
    engine: postgres
    plan: free
    ipAllowList: []
    version: "15"
